In [1]:
%load_ext autoreload
%autoreload 2

from explain.utils.kg_client import KGClient
client = KGClient()

### Gene

In [2]:
from explain.utils.entity import GeneEntity, CompoundEntity

In [3]:
gene1 = await GeneEntity.from_name("BRCA1")

In [4]:
gene2 = await GeneEntity.from_id("ENSG00000012048")

In [5]:
gene1 == gene2

True

In [19]:
gene1.symbol

'BRCA1'

#### Get labelled interactions between genes

Remember computing the id (ensembl id) and loading from the ensembl id is always better than trying to do it with the gene symbol

In [24]:
from explain.utils.entity import GeneEntity
import pandas as pd

gene = await GeneEntity.from_name("JAK1")
gene2 = await GeneEntity.from_name("STAT3")
out = await gene.get_process_interaction(gene2)
print(out)
pd.DataFrame.from_records(out) # if you want to see the data as a dataframe

2025-09-04 13:30:44.257 | DEBUG    | explain.utils.entity:get_process_interaction:30 - Found 127 interactions between JAK1 and STAT3

[{'relationship_type': 'shared_pathway', 'relationship': 'Signaling Pathways', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Signal Transduction', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interferon Signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Signaling by Interleukins and related cytokines', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Signaling by Interleukins', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Signaling by CSF3 (G-CSF)', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-15 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-9 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-21 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-2 family signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-6 family signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-20 family signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-10 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Inactivation of CSF3 (G-CSF) signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-4 and Interleukin-13 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-27 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-35 Signalling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-12 family signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Cytokine Signaling in Immune system', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-6 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Disease', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Antiviral mechanism by IFN-stimulated genes', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Interleukin-7 signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Immune System', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Immune System signaling', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Signaling in Immune system', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1,STAT3,STAT6 phosphorylation', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1,STAT3,STAT6 bind IL13:IL13R type II', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3,p-Y641-STAT6 dissociate', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'JAK1 phosphorylates STAT3,STAT6', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3,STAT6 bind p-Y-IL4R', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3 dissociates from  IL22:p-Y251,p-Y301-IL22RA1:p-JAK1:IL10RB:p-TYK2:p-Y705-STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3 dissociates from the IL22:p-Y251,p-Y301-IL22RA1:p-JAK1:PTPN11:IL10RB:p-TYK2:p-Y705-STAT3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 dissociates from the IL22 receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Phosphorylated STATs are released', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT1 and p-STAT3 dissociates from IL26:IL10RB:p-TYK2:IL20RA:p-JAK1', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1,STAT3 are phosphorylated by IL26:IL10RB:p-TYK2:IL20RA:p-JAK1:STAT1', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1 binds IL26:IL10RB:p-TYK2:IL20RA:p-JAK1 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL26:IL10RB:p-TYK2:IL20RA:p-JAK1 binds STAT1, STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1 binds IL10RB from phosphorylated IL26 receptor', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL15:IL15RA:p-Y-IL2RB:p-Y-JAK1:p-Y-IL2RG:p-Y-JAK3 phosphorylates STAT3 and STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated after IL15-IL15 receptor interaction', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL15:IL15RA:p-Y-IL2RB:p-Y-JAK1:p-Y-IL2RG:p-Y-JAK3 binds STAT3 and STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y-STAT3 and p-STAT5 dissociates from IL15:IL15RA:IL2RB:p-JAK1:IL2RG:p-JAK3:p-Y-STAT3:p-STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT3 dissociates from IL15:IL15R', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL9:p-Y407-IL9R:JAK1:IL2RG:p-904,939-JAK3:p-Y705-STAT3 dissociates from p-Y-STAT1, p-Y705-STAT3, p-STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y701-STAT1, p-Y705-STAT3, p-Y649-STAT5 dissociates from IL9:p-Y407-IL9R:JAK1:IL2RG:p-904,939-JAK3:p-Y705-STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL9:p-Y407-IL9R:JAK1:IL2RG:p-904,939-JAK3 binds STAT1, STAT3, STAT5A or STAT5B', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1, STAT3 or STAT5 bind IL9:p-Y407-IL9R:JAK1:IL2RG:p-904,939-JAK3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL9:p-Y116-IL9R:JAK1:IL2RG:p-904,939-JAK3:STAT3 phosphorylates STAT1, STAT3 or STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1, STAT3 or STAT5 are phosphorylated by IL9:p-Y116-IL9R:JAK1:IL2RG:p-904,939-JAK3:STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL21 receptor STAT phosphorylation', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL21 receptor STAT binding', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STATs bind gp130 phosphotyrosines', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Tyrosine phosphorylated IL6ST binds STAT1,STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Tyrosine phosphorylation of STAT1, STAT3 by IL6 receptor', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'Serine phosphorylation of STATs', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL24:IL22RA1:p-JAK1:IL20RB:STAT3 phosphorylates STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'stat3 is phosphorylated by il22r il20rb receptor activated complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated by IL19:IL20RA:p-JAK1:IL20RB:STAT3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated by IL19/IL19 receptor activated complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL19:IL20RA:p-JAK1:IL20RB:STAT3 phosphorylates STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds to IL19:IL20RA:p-JAK1:IL20RB activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds to IL19:IL20RA:p-JAK1:IL20RB', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL19:IL20RA:p‑JAK1:IL20RB binds STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds to IL19-IL19 activated Receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL20:IL20RA:JAK1:IL20RB:p‑JAK2,p‑JAK3 binds STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT5 binds to Activated IL20 IL20 Receptor JAK2 complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT5 binds to IL20:IL20RA:JAK1:IL20RB:p-JAK2,p-JAK3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT3 dissociates from IL24:IL22RA1:p-JAK1:IL20RB:p-STAT3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-stat3 dissociates from il22r il20rb receptor activated complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT3 dissociates from IL24:IL22RA1:p‑JAK1:IL20RB:p‑STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds to IL24:IL22RA1:p-JAK1:IL20RB', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT1,p-STAT3 dissociate from IL24:IL20RA:p-Y1022,Y1023-JAK1:IL20RB:p-STAT1, p-STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT3 dissociates from IL24:IL24 receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3 dissociates from IL10 dimer:2xp-Y-IL10RA:p-Y-JAK1:2xIL10RB:p-Y-TYK2:p-Y705-STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL10 dimer:2xp-Y-IL10RA:p-Y-JAK1:2xIL10RB:p-Y-TYK2 binds STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated by p-Y-JAK1,P-Y-TYK2', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL10 dimer:2xp-Y-IL10RA:p-Y-JAK1:2xIL10RB:p-Y-TYK2:STAT3 phosphorylates IL10 dimer:2xp-Y-IL10RA:p-Y-JAK1:2xIL10RB:p-Y-TYK2:STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL24:IL20RA:p-JAK1:IL20RB:STAT1,STAT3 phosphorylates STAT1 or STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated by IL24:p-IL20RA:p-JAK1:IL20RB:STAT3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated in IL24:IL24 receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL24:p-IL20RA:p-JAK1:IL20RB binds STAT1,STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds IL24:p-IL20RA:p-JAK1:IL20RB activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds p-IL20RA from IL24:IL24 receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p‑Y705-STAT3 dissociates from IL19:IL20RA:p-JAK1:IL20RB', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3 dissociates from IL19/IL19 receptor activated complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3 dissociates from IL19:IL20RA:p-JAK1:IL20RB:p-Y705', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3 dissociates from IL19:IL20RA:p-JAK1:IL20RB:p-Y705-STAT3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y705-STAT3 dissociates from IL20RA:IL20RB:IL19,IL20,IL24:p-Y705-STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated by IL22:p-Y251,p-Y301-IL22RA1:p-JAK1:PTPN11:IL10RB:p-TYK2:STAT3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 is phosphorylated by the IL22 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL22:p-Y251,p-Y301-IL22RA1:p-JAK1:IL10RB:p-TYK2:STAT3 phosphorylates STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds to IL22:p-Y251,p-Y301-IL22RA1:p-JAK1:PTPN11:IL10RB:p-TYK2:STAT3 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 binds IL22 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL22:p-Y251,p-Y301-IL22RA1:p-JAK1:PTPN11:IL10RB:p-TYK2 binds STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y-JAK1,2 phosphorylates STAT1,3,5 in CSF3 dimer:2xp-4Y-CSF3R:LYN:p-Y-JAK1:p-Y-JAK2:p-TYK2', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'CSF3 dimer:2xp-4Y-CSF3R:LYN:p-Y-JAK1:p-JAK2:p-SYK:p-HCK:p-TYK2 binds STAT1,3,5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'CSF3 dimer:2xp-4Y-CSF3R:LYN:p-Y-JAK1:p-JAK2:p-SYK:p-HCK:p-TYK2:p-Y-STAT1,3,5 dissociates yielding CSF3 dimer:2xp-4Y-CSF3R:LYN:p-Y-JAK1:p-JAK2:p-SYK:p-HCK:p-TYK2 and p-Y-STAT1,3,5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT1 dissociates from IFNL1:p-Y343-Y517-IFNLR1:p-JAK1:IL10RB:p-TYK2:p-STAT1 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT1, p-Y-STAT2, p-STAT3, p-STAT4, p-STAT5 dissociates from IFNL1:p-Y343,Y517-IFNLR1:p-JAK1:IL10RB:p-TYK2:p-STAT1,p-STAT2,p-STAT3,p-STAT4,p-STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'phosphorylated STAT1  dissociates from IL29-IL29 receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IFNL1:p-Y343,Y517-IFNLR1:p-JAK1:IL10RB:p-TYK2:STAT1 phosphorylates STAT1, STAT2, STAT3, STAT4 and STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1 is phosphorylated after IL29-IL29 receptor interaction', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1 is phosphorylated by IFNL1:p-Y343-Y517-IFNLR1:p-JAK1:IL10RB:p-TYK2:STAT1 activated receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IFNL1:p-Y434,Y517-IFNLR1:p-JAK1:IL10RB:p-TYK2 binds STAT1, STAT2, STAT3, STAT4, STAT5', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT3 dissociates from IL20:IL20RA:JAK1:IL20RB:p-Y1007,Y1008-JAK2,p-JAK3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'IL20:IL20RA:JAK1:IL20RB:p-JAK3,p-JAK2:STAT3 phosphorylates STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y-STATs dissociate', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT3 and STAT1 are phosphorylated by JAKs after IL27:IL27R interaction', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-Y701-STAT1 and p-Y705-STAT3 dissociate from IL27:IL27 receptor', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1, STAT3 bind p-Y611-IL27RA from Interleukin-27:Interleukin-27 receptor complex', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'p-STAT1, p-STAT3 dissociate from IL27RA:IL12RB2 receptor', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'JAK1,JAK2 bound to IL27RA:IL12RB2 receptor phosphorylate STAT1,STAT3', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_pathway', 'relationship': 'STAT1,STAT3 associate with IL27RA:IL12RB2 receptor', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_function', 'relationship': 'cell differentiation', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_function', 'relationship': 'interleukin-6-mediated signaling pathway', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_function', 'relationship': 'cell surface receptor signaling pathway via JAK-STAT', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type': 'shared_function', 'relationship': 'T-helper 17 cell lineage commitment', 'gene1_symbol': 'JAK1', 'gene2_symbol': 'STAT3'}, {'relationship_type'

,relationship_type,relationship,gene1_symbol,gene2_symbol
0,shared_pathway,Signaling Pathways,JAK1,STAT3
1,shared_pathway,Signal Transduction,JAK1,STAT3
2,shared_pathway,Interferon Signaling,JAK1,STAT3
3,shared_pathway,Signaling by Interleukins and related cytokines,JAK1,STAT3
4,shared_pathway,Signaling by Interleukins,JAK1,STAT3
...,...,...,...,...
122,shared_function,interleukin-10-mediated signaling pathway,JAK1,STAT3
123,shared_function,interleukin-2-mediated signaling pathway,JAK1,STAT3
124,shared_function,interleukin-9-mediated signaling pathway,JAK1,STAT3
125,shared_function,interleukin-15-mediated signaling pathway,JAK1,STAT3
126,shared_function,interleukin-11-mediated signaling pathway,JAK1,STAT3

##### Get the summary description of a gene based on annotations from unitprot, etc with known evidence

In [29]:
await gene2.get_summary()

'Signal transducer and transcription activator that mediates cellular responses to interleukins, KITLG/SCF, LEP and other growth factors (PubMed:10688651, PubMed:12359225, PubMed:12873986, PubMed:15194700, PubMed:15653507, PubMed:16285960, PubMed:17344214, PubMed:18242580, PubMed:18782771, PubMed:22306293, PubMed:23084476, PubMed:28262505, PubMed:32929201, PubMed:38404237). Once activated, recruits coactivators, such as NCOA1 or MED1, to the promoter region of the target gene (PubMed:15653507, PubMed:16285960, PubMed:17344214, PubMed:18782771, PubMed:28262505, PubMed:32929201). May mediate cellular responses to activated FGFR1, FGFR2, FGFR3 and FGFR4 (PubMed:12873986). Upon activation of IL6ST/gp130 signaling by interleukin-6 (IL6), binds to the IL6-responsive elements identified in the promoters of various acute-phase protein genes (PubMed:12359225). Activated by IL31 through IL31RA (PubMed:15194700). Acts as a regulator of inflammatory response by regulating differentiation of naive CD4(+) T-cells into T-helper Th17 or regulatory T-cells (Treg): acetylation promotes its transcription activity and cell differentiation while deacetylation and oxidation of lysine residues by LOXL3 inhibits differentiation (PubMed:28065600, PubMed:28262505). Involved in cell cycle regulation by inducing the expression of key genes for the progression from G1 to S phase, such as CCND1 (PubMed:17344214). Mediates the effects of LEP on melanocortin production, body energy homeostasis and lactation (By similarity). May play an apoptotic role by transctivating BIRC5 expression under LEP activation (PubMed:18242580). Cytoplasmic STAT3 represses macroautophagy by inhibiting EIF2AK2/PKR activity (PubMed:23084476). Plays a crucial role in basal beta cell functions, such as regulation of insulin secretion (By similarity). Following JAK/STAT signaling activation and as part of a complex with NFATC3 and NFATC4, binds to the alpha-beta E4 promoter region of CRYAB and activates transcription in cardiomyocytes (By similarity)'

##### Get the annotation on a particular gene

In [30]:
await gene2.get_annotations()

2025-09-04 13:33:47.682 | DEBUG    | explain.utils.entity:get_annotations:314 - Retrieved 8 annotation categories for gene: STAT3

,category,annotation_count,annotations
0,Biological Processes,37,positive regulation of angiogenesis | regulati...
1,Cellular Location,5,regulation of multicellular organism growth | ...
2,Gene Groups,1323,GOBP_REGULATION_OF_IMMUNE_SYSTEM_PROCESS | ZNF...
3,Gene Synonyms,2,APRF | signal transducer and activator of tran...
4,Molecular Functions,65,nervous system development | response to lepti...
5,Protein Domains,3,SH2_STAT3 | STAT3_CCD | STAT3_DBD
6,Signaling Pathways,60,Signaling by MET | Signaling Pathways | Signal...
7,Tissue Expression,5,pancreas | kidney | placenta | adult mammalian...

## Chemical

In [8]:
from explain.utils.entity import CompoundEntity

compound1 = await CompoundEntity.from_id("CHEMBL25")
compound1

[13:23:57] Initializing Normalizer
[13:23:57] Running Normalizer
/Users/emmanuel.noutahi/Code/hooke-explain/.venv/lib/python3.12/site-packages/google/cloud/bigquery/table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

CompoundEntity(id='BSYNRYMUTXBXSQ-UHFFFAOYSA-N', name='ASPIRIN', synonyms=['Anadin all night', 'Gencardia', 'Acetylsalic acid', 'ACETYLSALICYLIC ACID', 'Acidum acetylsalicylicum', 'Durlaza', 'NSC-27223', 'SID90340586', 'Salicylic Acid Acetate', 'Aspirine', 'Acetosalic Acid', 'Measurin', 'Acetyl salicyclic acid', '2-Acetoxy-benzoic acid', 'ASPIRIN', 'Platet', 'Nu-seals 75', 'SID144210466', 'ASPIRINE', 'SID144203627', 'Acetylsalicylic acid', 'SID17390036', 'Acetyl Salicylic acid', 'Acetylsalicylate', 'Acetylsalicylic acid; Aspirin', 'SID144209315', 'Postmi 300', 'Aspirin', 'Acetyl salicylate', 'Alka rapid', '2-(acetyloxy)benzoic acid', 'Enprin', 'Paynocil', 'acetylsalicylic acid', '2-acetoxybenzoate', '2-acetyloxybenzoic acid', '2-(methoxycarbonyl)benzoic acid', 'SID174007205', 'Equi-Prin', 'SID26752858', 'Bayer extra strength aspirin for migraine pain', 'Platet 300', 'NSC-406186', 'Ecotrin', 'aspirin', '2-Acetoxy-benzoic acid (aspirin)', 'Acetylsalicyclic acid', 'SID17389202', 'SID170465039', 'o-acetylsalicylic acid', 'Acetylsalicylicum acidum', 'SID87798', 'Danamep', '(aspirin)2-Acetoxy-benzoic acid', 'Asparin', 'Micropirin ec', 'Postmi 75', 'Nu-seals cardio 75', 'Acetylsalicylic Acid', 'Acetyl salicylic acid', 'BAY1019036', 'Aspro clr', 'Benzoic acid, 2-(acetyloxy)-', 'Disprin cv', 'Acetylsalicylic acid (who-ip)', 'Asprin', 'SID26747283', 'Vazalore', 'acetyl salicylic acid', 'Levius', '8-hour bayer', 'SID50105490', 'Max strgh aspro clr', 'Nu-seals 300', 'SID85230910', '2-acetoxybenzoic acid', 'Angettes 75', 'Disprin direct', 'SID47193676', 'Nu-seals 600'], chembl_id='CHEMBL25', smiles='CC(=O)Oc1ccccc1C(=O)O', inchikey='BSYNRYMUTXBXSQ-UHFFFAOYSA-N', pubchem_cid='2244', rec_id='REC-0001392', dose=None)

In [9]:
compound2 = await CompoundEntity.from_id("BSYNRYMUTXBXSQ-UHFFFAOYSA-N")
compound2

/Users/emmanuel.noutahi/Code/hooke-explain/.venv/lib/python3.12/site-packages/google/cloud/bigquery/table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

CompoundEntity(id='BSYNRYMUTXBXSQ-UHFFFAOYSA-N', name='ASPIRIN', synonyms=['8-HOUR BAYER', 'Acetosalic Acid', 'ACETYL SALICYLATE', 'ACETYLSALIC ACID', 'ACETYLSALICYLIC ACID', 'ACETYLSALICYLIC ACID (WHO-IP)', 'ACETYLSALICYLICUM ACIDUM', 'ACIDUM ACETYLSALICYLICUM', 'ACIDUM ACETYLSALICYLICUM (WHO-IP)', 'ALKA RAPID', 'ANADIN ALL NIGHT', 'ANGETTES 75', 'ASPIRIN', 'ASPRO CLR', 'BAY1019036', 'BAYER EXTRA STRENGTH ASPIRIN FOR MIGRAINE PAIN', 'BENZOIC ACID, 2-(ACETYLOXY)-', 'DANAMEP', 'DISPRIN CV', 'DISPRIN DIRECT', 'DURLAZA', 'Ecotrin', 'ENPRIN', 'Equi-Prin', 'GENCARDIA', 'LEVIUS', 'MAX STRGH ASPRO CLR', 'MEASURIN', 'MICROPIRIN EC', 'NSC-27223', 'NSC-406186', 'NU-SEALS 300', 'NU-SEALS 600', 'NU-SEALS 75', 'NU-SEALS CARDIO 75', 'PAYNOCIL', 'PLATET', 'PLATET 300', 'POSTMI 300', 'POSTMI 75', 'Salicylic Acid Acetate', 'VAZALORE'], chembl_id='CHEMBL25', smiles='CC(=O)Oc1ccccc1C(=O)O', inchikey='BSYNRYMUTXBXSQ-UHFFFAOYSA-N', pubchem_cid=None, rec_id='REC-0001392', dose=None)

In [10]:

compound3 = await CompoundEntity.from_name("Aspirin")
compound3.to_dict()

/Users/emmanuel.noutahi/Code/hooke-explain/.venv/lib/python3.12/site-packages/google/cloud/bigquery/table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

{'id': 'BSYNRYMUTXBXSQ-UHFFFAOYSA-N',
 'name': 'ASPIRIN',
 'synonyms': ['aspirin',
  'ACETYLSALICYLIC ACID',
  '50-78-2',
  '2-Acetoxybenzoic acid',
  '2-(Acetyloxy)benzoic acid',
  'O-Acetylsalicylic acid',
  'o-Acetoxybenzoic acid',
  'Acylpyrin',
  'Ecotrin',
  'Salicylic acid acetate',
  'Acenterine',
  'Acetophen',
  'Polopiryna',
  'Acetosalin',
  'Aspirdrops',
  'o-Carboxyphenyl acetate',
  'Pharmacin',
  'Premaspin',
  'Salcetogen',
  'Aceticyl',
  'Acetonyl',
  'Acidum acetylsalicylicum',
  'Benaspir',
  'Empirin',
  'Endydol',
  'Measurin',
  'Rhodine',
  'Saletin',
  'Temperal',
  'Ecolen',
  'Rheumintabletten',
  'Solprin acid',
  '2-acetyloxybenzoic acid',
  'Enterosarine',
  'Acetisal',
  'Acetylsal',
  'Aspirine',
  'Bialpirina',
  'Bialpirinia',
  'Entericin',
  'Enterophen',
  'Globentyl',
  'Salacetin',
  'Solpyron',
  'Acesal',
  'Acisal',
  'Asagran',
  'Asteric',
  'Caprin',
  'Cemirit',
  'Duramax',
  'Extren',
  'Globoid',
  'Helicon',
  'Idragin',
  'Levius',
  'Rhonal',
  'Adiro',
  'Aspro',
  'Novid',
  'Yasta',
  'Acetosalic acid',
  'Benzoic acid, 2-(acetyloxy)-',
  'Acimetten',
  'Delgesic',
  'Entrophen',
  'Acetilum acidulatum',
  'Acetilsalicilico',
  '2-Carboxyphenyl acetate',
  'Dolean pH 8',
  'Contrheuma retard',
  'XAXA',
  'Acido acetilsalicilico',
  'Acide acetylsalicylique',
  'Bayer',
  '8-hour Bayer',
  'Asatard',
  'Durlaza',
  'Ronal',
  'Rheumin tabletten',
  '2-Acetoxybenzenecarboxylic acid',
  'acetyl salicylate',
  'Acetylsalicylsaeure',
  'Azetylsalizylsaeure',
  'SP 189',
  'AC 5230',
  'Acetylsalicyclic acid',
  'Acetylsalicylicum acidum',
  'DTXSID5020108',
  'CHEBI:15365',
  'o-(Acetyloxy)benzoic acid',
  'NSC-27223',
  'acide 2-(acetyloxy)benzoique',
  'Bayer Extra Strength Aspirin for Migraine Pain',
  'NSC-406186',
  'R16CO5Y76E',
  'BAY1019036',
  'DTXCID50108',
  'DUOCOVER COMPONENT ASPIRIN',
  'YOSPRALA COMPONENT ASPIRIN',
  'DUOPLAVIN COMPONENT ASPIRIN',
  'NSC406186',
  'CLOPIDOGREL/ACETYLSALICYLIC ACID COMPONENT ASPIRIN',
  'Acid, Acetylsalicylic',
  'vetality',
  'Ascurin',
  'Danamep',
  'Fasprin',
  'Gencardia',
  'Medpurine',
  'Paynocil',
  'Enprin',
  'Platet',
  'Disprin direct',
  'Micropirin ec',
  'Solves-aspirin',
  'Aramark Aspirin',
  'Aspirin Powder',
  'Aspirin Regimen',
  'Canine Aspirin',
  'Clopidogrel Kit',
  'Coated Aspirin',
  'Enteric Aspirin',
  'Equate Aspirin',
  'Leader Aspirin',
  'Medique Aspirin',
  'Rapidol Aspirin',
  'Sunmark Aspirin',
  'Topcare Aspirin',
  'Acetylsalic acid',
  'Alka rapid',
  'Aspirin Bolus',
  'Aspirin Nsaid',
  'Aspirin Packs',
  'AspirinLow Dose',
  'Bayer Aspirin',
  'Disprin cv',
  'Pain Reliever',
  'Rugby Aspirin',
  'Value Pharma',
  'Aspro clr',
  'Aspi-cor',
  'Aspirin Chewable',
  'Buffered Aspirin',
  'Chewable Aspirin',
  'Geritrex Aspirin',
  'Plus Pharma',
  'Regular Strength',
  'Thompson Aspirin',
  'McKesson Aspirin',
  'Anadin all night',
  'Aspir Low',
  'Equi-Prin',
  'Aspirin EC',
  'Childrens Aspirin',
  'Unishield Aspirin',
  'Adult Low Dose',
  'Bayer Low Dose',
  'Aspirin 5 Grain',
  'Aspirin Low Dose',
  'Low Dose Aspirin',
  'Bufferin Arthritis',
  'ULINE Aspirin',
  'CAREALL Aspirin',
  'Aspica (Aspirin)',
  'Aspirin 81mg',
  'Dg Health Aspirin',
  'Low Dose Miniprin',
  'Angettes 75',
  'Medi-first Aspirin',
  'aspirin pain relief',
  'Basic Care Aspirin',
  'Good Sense Aspirin',
  'Aspirin 325mg',
  'Aspirin 81',
  'Aspirin 81 mg',
  'Health Mart Aspirin',
  'MBR Aspirin Powder',
  'Pain Relief Aspirin',
  'Max strgh aspro clr',
  'AsCurin Fast Action',
  'Aspirin 325 mg',
  'Aspirin Pain reliver',
  'Postmi 75',
  'RefChem:17',
  'Tri-buffered Aspirin',
  'Aspirin 325',
  'Aspirin 50 CT',
  'Aspirin Low Strength',
  'ASPIRN',
  'ASPRISOL',
  'Crane Safety Aspirin',
  'Henry Schein Aspirin',
  'Nu-seals 75',
  'Travel Savvy Aspirin',
  'VAZALORE',
  'Solves-aspirin Cherry',
  'Adult Aspirin Regimen',
  'Aspirin Bolus-240',
  'Bayer Aspirin Regimen',
  'Bayer Genuine Aspirin',
  'Direct Safety Aspirin',
  'Nu-seals cardio 75',
  'Rapid Comfort Aspirin',
  'MEDIQUE ASPIRN',
  'Platet 300',
  'Postmi 300',
  'Nu-seals 300',
  'Nu-seals 600',
  'Adult Chewable Aspirin',
  'Aspirin Enteric Coated',
  'Aspirin Extra Strength',
  'Enteric Coated Aspirin',
  'Extra Strength Aspirin',
  'ADVANCED ASPIRIN',
  'VALUMEDS ASPIRIN',
  'Aspirin Delayed Release',
  'Aspirin tablet 325mg',
  'Chewable Aspirin 81mg',
  'Dye-Free Aspirin 81',
  'Equate Aspirin Chewable',
  'Physicians Care Aspirin',
  'Adult Low Dose Aspirin',
  'Aspirin Adult Low Dose',
  'Low dose aspirin 81mg',
  'Medique at Home Aspirin',
  'Aspirin 81mg Dye-Free',
  'Aspirin Regular Strength',
  'Ecotrin Regular Strength',
  'Leader Low Dose Aspirin',
  'Medi-First Plus Aspirin',
  'Medique Products Aspirin',
  'Regular Strength Aspirin',
  'Circle K Aspirin 325',
  'Pharbest Aspirin 325mg',
  'foster and thrive aspirin',
  'AquaSource Aspirin Powder',
  'AspirinLow Dose Low Dose',
  'Value PharmaPain Reliever',
  'meijer LOW DOSE Aspirin',
  'Aspirin Chewable Low Dose',
  'Aspirin Liquid Concentrate',
  'Aspirin Low Dose Chewable',
  'BAYER 500 mg',
  'Chewable Aspirin Low Dose',
  'Chewable Low Dose Aspirin',
  'Chronic Pain/Fever Relief',
  'Low Dose Chewable Aspirin',
  'Aspirin 81 Mg Low Dose',
  'aspirin chewable, low dose',
  'CARDIASPIRIN PROTECT',
  'NobleAid PAIN RELIEVER',
  'Acetylsalicylic Acid Coated',
  'Adult Low Strength Aspirin',
  'ASPIRIN 480',
  'Up and Up Chewable Aspirin',
  'ASPIRIN BOLUS-480',
  'Regular Strength Aspirin EC',
  'Plus Pharma Nsaid 325 mg',
  'Alka-Seltzer Original Flavor',
  'Aspirin 81mg Enteric coated',
  'Critical Care Aspirin To Go',
  'ASPIRIN 325 MG EC',
  'HEB Effervescent Pain Relief',
  'Adult Low Dose Pain Reliever',
  'Aspirin Enteric Safety Coated',
  'Aspirin Enteric Safety-coated',
  'Dr. Waynes Aspirin Low Dose',
  'Family Wellness Pain Reliever',
  'Low Strength Chewable Aspirin',
  'Pain Relief Aspirin Low Dose',
  'St. Joseph Low Dose Aspirin',
  'Aspirin 81mg Adult Low Dose',
  'BAYER Aspirin Extra Strength',
  'Lil Drug Store Aspirin 325',
  'Aspirin 81 mg Enteric Coated',
  'Aspirin Low Strength, Enteric',
  'Bayer Aspirin Regimen Chewable',
  'Bayer Chewable-Aspirin Regimen',
  'Good Neighbor Pharmacy Aspirin',
  'Rapidol Aspirin Display 2x25',
  'CVS Effervescent Pain Reliever',
  'Adult Aspirin Regimen Low Dose',
  'Aspirin Low Dose Safety Coated',
  'Meijer Effervescent Pain Relief',
  'Chewable Aspirin Adult low dose',
  'Aspen Aspirin Liquid Concentrate',
  'Aspirin Enteric Coated Low Dose',
  'Aspirin Low Dose Enteric Coated',
  'Buffered Aspirin For Small Dogs',
  'Chewable Adult Low Dose Aspirin',
  'MBR Aspirin Bolus 240 Grains',
  'TopCare Effervescent Pain Relief',
  'Aspirin Low Dose Chewable Orange',
  'Pharbest Regular Strength Aspirin',
  'First Aid Direct Chewable Aspirin',
  'Regular Strength Aspirin 325 mg',
  'Pain Reliever / Low Dose Aspirin',
  'Drug Mart Effervescent Pain Relief',
  'Equaline Effervescent Pain Reliever',
  'Sunmark Aspirin Adult Low Strength',
  'Value Pharma Aspirin Pain Reliever',
  'Good Sense Effervescent Pain Relief',
  'AquaPrime Aspirin Liquid Concentrate',
  'Bayer Aspirin Regimen enteric coated',
  'Green Guard Chewable Aspirin 81 mg',
  'AquaSource Aspirin Liquid Concentrate',
  'Bayer Aspirin Extra Strength Caplets',
  'Buffered aspirin, effervescent tablet',
  'Winco Foods Effervescent Pain Relief',
  'Bufferin Regular Strength Pain Relief',
  'Adult Low Dose Aspirin Enteric Coated',
  'Adult Low Dose Enteric Coated Aspirin',
  'Aspirin Enteric Coated Tablets 81 mg',
  'BAYER Aspirin Original, CVP HEALTH',
  'Market Basket Effervescent Pain Relief',
  'St. Joseph Chewable Low Dose Aspirin',
  'Aspirin 81 mg Delayed Release Tablets',
  'Low Dose Aspirin Enteric Safety Coated',
  'Low Dose Aspirin Enteric Safety-Coated',
  'Safety Coated Aspirin 81 mg Low Dose',
  'Acido Acetilsalicilico With enteric coat',
  'BAYER Aspirin Original, TRAVEL BASIX',
  'Enteric Coated Aspirin Regular Strength',
  'Low Dose Miniprin Enteric Safety Coated',
  'Pain Relief Aspirin Chewable, Low Dose',
  'Quality Choice Effervescent Pain Relief',
  'Regular Strength Enteric Coated Aspirin',
  'Right Remedies Aspirin Low Dose 81 mg',
  'Aspirin Delayed Release Tablets, 81 mg',
  'Aspirin Enteric Coated, Regular Strength',
  'Coraspirin 81 mg Enteric Coasted Tablet',
  'FIRST CHOICE ASPIRIN BOLUS-480grs',
  'Value Pharmapain Reliever Extra Strength',
  'Dollar General Effervescent Pain Reliever',
  'Best Choice Effervescent Pain Reliever 36',
  'Buffered Aspirin For Medium to Large Dogs',
  'Cardioaspirin 81 mg Enteric Coated Tablet',
  'Medique Products Chewable Low Dose Aspirin',
  'FIRST CHOICE dairy supply ASPIRIN BOLUS',
  'Aspirin 81mg Enteric coated Delayed Release',
  'Adult Low Dose Aspirin Enteric Safety Coated',
  'Publix Fast Relief Effervescent-Original Flavor',
  'Safety Coated Aspirin 325 mg Regular Strength',
  'Coraspirina 81 mg Tabletas con cubierta enterica',
  'Gencare-Aspirin Low Dose Pain reliever (NSAID)',
  'Cardiospirina 81 mg Tabletas con cubierta enterica',
  'Natural Aspirin plus Tart Cherry Dietary Supplement',
  'ASPIRIN LOW DOSE CHEWABLE ORANGE PAIN RELIEVER',
  'Bayer Aspirin Regimen Chewable Low Dose Aspirin Orange',
  'Aspirin 81mg Enteric coated Low Strength Aspirin Regimen',
  'Natural Aspirin plus Immune Supporting Dietary Supplement',
  'Natural Aspirin plus Lemon and Honey Dietary Supplement',
  'Bayer Chewable-Aspirin Regimen Low Dose Aspirin Cherry Flavored',
  '200-064-1',
  'Acetosal',
  'Easprin',
  'Colfarit',
  'Enterosarein',
  'Acetylin',
  'Micristin',
  'Claradin',
  'Clariprin',
  'Neuronika',
  'Decaten',
  'Pirseal',
  'Solfrin',
  'Aspec',
  'Triple-sal',
  'Spira-Dine',
  'ZORprin',
  'Bi-prin',
  'Persistin',
  'A.S.A. empirin',
  'ASA',
  'Endosprin',
  'Kapsazal',
  'Solprin',
  'Acetylsalicylsaure',
  'acetyl salicylic acid',
  'Tasprin',
  'Nu-seals aspirin',
  'Salicylic acid, acetate',
  'Acido O-acetil-benzoico',
  'Kyselina acetylsalicylova',
  'St. Joseph Aspirin for Adults',
  'A.S.A.',
  'St. Joseph',
  'Kyselina 2-acetoxybenzoova',
  'Acetard',
  'S-211',
  'MFCD00002430',
  'Aspirin (Standard)',
  'ECM',
  '2-(acetyloxy)benzoate',
  'benzoic acid, 2-acetoxy-',
  'Acetylsalicylic acid (who-ip)',
  'Aspirin form II',
  'component of Midol',
  'NSC27223',
  'component of Synirin',
  'component of Zactirin',
  'component of Coricidin',
  'component of Persistin',
  'component of Robaxisal',
  'o-Acetoxybenzoate',
  'NCGC00015067-04',
  'Acetysal',
  'ACIDUM ACETYLSALICYLICUM (WHO-IP)',
  'Istopirin',
  'Magnecyl',
  'Medisyl',
  'Polopirin',
  'Bayer Buffered',
  'Aspro Clear',
  'component of Ascodeen-30',
  'Bayer Plus',
  'WLN: QVR BOV1',
  'aspirin (acetylsalicylic acid)',
  'Aspirina 03',
  'Acetylsalycilic acid',
  'component of Darvon with A.S.A',
  'Bayer Aspirin 8 Hour',
  'Asaphen',
  'Aspalon',
  'Asprin',
  "Bayer Children's Aspirin",
  'Nu-seals',
  'component of St. Joseph Cold Tablets',
  'Aspir-Mox',
  'Durlaza ER',
  'Acetylsalicylsaure [German]',
  'CAS-50-78-2',
  'Acetoxybenzoic acid',
  'Acetysalicylic acid',
  'AIN',
  'SMR000059138',
  'Ascoden-30',
  'CCRIS 3243',
  'HSDB 652',
  'Acide acetylsalicylique [French]',
  'Acido acetilsalicilico [Italian]',
  'Kyselina acetylsalicylova [Czech]',
  'Acido O-acetil-benzoico [Italian]',
  'SR-01000075668',
  'Kyselina 2-acetoxybenzoova [Czech]',
  'EINECS 200-064-1',
  'NSC 27223',
  'Aspirin [USP:BAN:JAN]',
  'Bayer Enteric 325 mg Regular Strength',
  'BRN 0779271',
  'Bay E4465',
  'UNII-R16CO5Y76E',
  'Aspropharm',
  'Bayer Enteric 81 mg Adult Low Strength',
  'Cardioaspirin',
  'Cardioaspirina',
  'Acetyonyl',
  'Asacard',
  'Ascolong',
  'Bayer Enteric 500 mg Arthritis Strength',
  'Colsprin',
  'Miniasal',
  'Salospir',
  'Acesan',
  'Toldex',
  'AI3-02956',
  '1oxr',
  '2-Acetoxybenzoate',
  'Aspalon (JAN)',
  'Durlaza (TN)',
  'Easprin (TN)',
  'acetyl-salicylic acid',
  'acetyl salicyclic acid',
  'o-(Acetyloxy)benzoate',
  'Percodan (Salt/Mix)',
  'Ascriptin (Salt/Mix)',
  'Micrainin (Salt/Mix)',
  '2-acetoxy benzoic acid',
  'Acetylsalicylic acidASA',
  'Spectrum_001245',
  '2-Acetylsalicyclic acid',
  'ASPIRIN [VANDF]',
  'ASPIRIN [HSDB]',
  'Salicylic acid, acetyl-',
  'ASPIRIN [JAN]',
  'ASPIRIN [MI]',
  'CHEMBL25',
  'ASPIRIN [MART.]',
  'Spectrum2_001899',
  'Spectrum3_001295',
  'Spectrum4_000099',
  'Spectrum5_000740',
  'Aspirin (JP18/USP)',
  'Lopac-A-5376',
  'Salycylacetylsalicylic acid',
  'ASPIRIN [USP-RS]',
  'Epitope ID:114151',
  'Percodan Demi (Salt/Mix)',
  'Soma Compound (Salt/Mix)',
  'EC 200-064-1',
  'PL2200 component aspirin',
  'Acetylsalicylic acid, 99%',
  'cid_2244',
  'Pravigard PAC (Salt/Mix)',
  'SCHEMBL1353',
  '2-(Acetyloxy)-benzoic acid',
  'Aspirin-PC component aspirin',
  'Bay-e-4465',
  'Lopac0_000038',
  'KBioGR_000398',
  'KBioGR_002271',
  'KBioSS_001725',
  'KBioSS_002272',
  '4-10-00-00138 (Beilstein Handbook Reference)',
  'MLS001055329',
  'MLS001066332',
  'MLS001336045',
  'MLS001336046',
  'ASPIRIN [ORANGE BOOK]',
  'BIDD:GT0118',
  'DivK1c_000555',
  'SPECTRUM1500130',
  'PA-32540 component aspirin',
  'SPBio_001838',
  'Acetylsalicylic acid, >=99%',
  'AXOTAL COMPONENT ASPIRIN',
  'AZDONE COMPONENT ASPIRIN',
  'CODOXY COMPONENT ASPIRIN',
  'GTPL4139',
  'orb1311035',
  'SCHEMBL1369714',
  'SCHEMBL6200251',
  'ASPIRIN [USP MONOGRAPH]',
  'O-Acetylsalicylic acid; Aspirin',
  'SCHEMBL29350479',
  'Acetylsalicylic acid-carboxy-14c',
  'AGGRENOX COMPONENT ASPIRIN',
  'BDBM22360',
  'EXCEDRIN COMPONENT ASPIRIN',
  'FIORINAL COMPONENT ASPIRIN',
  'HMS501L17',
  'KBio1_000555',
  'KBio2_001725',
  'KBio2_002271',
  'KBio2_004293',
  'KBio2_004839',
  'KBio2_006861',
  'KBio2_007407',
  'KBio3_002149',
  'KBio3_002751',
  'NORGESIC COMPONENT ASPIRIN',
  'PERCODAN COMPONENT ASPIRIN',
  'Q-GESIC COMPONENT ASPIRIN',
  'ROXIPRIN COMPONENT ASPIRIN',
  'VICOPRIN COMPONENT ASPIRIN',
  'Empirin with Codeine (Salt/Mix)',
  'MSK9019',
  'Acetylsalicylic acid, >=99.0%',
  'cMAP_000006',
  'component of Zactirin (Salt/Mix)',
  'EQUAGESIC COMPONENT ASPIRIN',
  'INVAGESIC COMPONENT ASPIRIN',
  'LANORINAL COMPONENT ASPIRIN',
  'MICRAININ COMPONENT ASPIRIN',
  'NINDS_000555',
  'ROBAXISAL COMPONENT ASPIRIN',
  'HMS1920E13',
  'HMS2090G03',
  'HMS2091K13',
  'HMS2233L18',
  'HMS3260G17',
  'HMS3372N15',
  'HMS3656N14',
  'HMS3715P19',
  'HMS3866L03',
  'HMS3885G03',
  'HMS5081M04',
  'HMS6018L04',
  'Pharmakon1600-01500130',
  'BCP21790',
  'ORPHENGESIC COMPONENT ASPIRIN',
  'STR01551',
  'ACETYLSALICYLIC ACID; ASPIRIN',
  'SYNALGOS-DC COMPONENT ASPIRIN',
  'Tox21_110076',
  'Tox21_202117',
  'Tox21_300146',
  'Tox21_500038',
  'CCG-39490',
  'HY-14654R',
  'NSC755899',
  's3017',
  'SBB015069',
  'STL137674',
  'ACETYLSALICYLIC ACID [WHO-DD]',
  'AKOS000118884',
  'component of Ascodeen-30 (Salt/Mix)',
  'MEPRO-ASPIRIN COMPONENT ASPIRIN',
  'PERCODAN-DEMI COMPONENT ASPIRIN',
  'PRAVIGARD PAC COMPONENT ASPIRIN',
  'SOMA COMPOUND COMPONENT ASPIRIN',
  'Tox21_110076_1',
  'ACETYLSALICYLIC ACID [EMA EPAR]',
  'ACETYLSALICYLICUM ACIDUM [HPUS]',
  'CS-2001',
  'DB00945',
  'FA17179',
  'LP00038',
  'NSC-755899',
  'PL-2200',
  'SDCCGSBI-0050027.P005',
  'BAY-1019036',
  'DARVON COMPOUND COMPONENT ASPIRIN',
  'IDI1_000555',
  'INVAGESIC FORTE COMPONENT ASPIRIN',
  'TALWIN COMPOUND COMPONENT ASPIRIN',
  'ACETYLSALICYLIC ACID [GREEN BOOK]',
  'Acetylsalicylic acid, analytical standard',
  'NCGC00015067-01',
  'NCGC00015067-02',
  'NCGC00015067-03',
  'NCGC00015067-05',
  'NCGC00015067-06',
  'NCGC00015067-07',
  'NCGC00015067-08',
  'NCGC00015067-09',
  'NCGC00015067-10',
  'NCGC00015067-11',
  'NCGC00015067-12',
  'NCGC00015067-13',
  'NCGC00015067-14',
  'NCGC00015067-24',
  'NCGC00015067-26',
  'NCGC00090977-01',
  'NCGC00090977-02',
  'NCGC00090977-03',
  'NCGC00090977-04',
  'NCGC00090977-05',
  'NCGC00090977-06',
  'NCGC00090977-07',
  'NCGC00254034-01',
  'NCGC00259666-01',
  'NCGC00260723-01',
  'AC-37704',
  'Aspirin, meets USP testing specifications',
  'DA-61272',
  'HY-14654',
  'NCI60_002222',
  'ORPHENGESIC FORTE COMPONENT ASPIRIN',
  'ST075414',
  'ACETYLSALICYLIC ACID [EP MONOGRAPH]',
  'SBI-0050027.P004',
  'DS-017139',
  'UNM-0000306102',
  'A2262',
  'component of Darvon with A.S.A (Salt/Mix)',
  'CS-0694916',
  'EU-0100038',
  'NS00000658',
  'SW199665-2',
  'CARISOPRODOL COMPOUND COMPONENT ASPIRIN',
  'EN300-19606',
  'A 5376',
  'Acetylsalicylic Acid 1.0 mg/ml in Acetonitrile',
  'C01405',
  'D00109',
  'E80792',
  'Q18216',
  'AB00051918-08',
  'AB00051918_09',
  'AB00051918_10',
  'F358239',
  'Arthritis Pain Formula Maximum Strength (Salt/Mix)',
  'SR-01000075668-1',
  'SR-01000075668-4',
  'SR-01000075668-6',
  'BRD-K11433652-001-16-2',
  'BRD-K11433652-001-17-0',
  'BRD-K11433652-001-18-8',
  'Acetylsalicylic acid, Vetec(TM) reagent grade, >=99%',
  'Aspirin, British Pharmacopoeia (BP) Reference Standard',
  'F2191-0068',
  'Z104474430',
  'Aspirin, United States Pharmacopeia (USP) Reference Standard',
  'D41527A7-A9EB-472D-A7FC-312821130549',
  'Acetylsalicylic acid, European Pharmacopoeia (EP) Reference Standard',
  'Acetylsalicylic acid, BioReagent, plant cell culture tested, >=99.0%',
  '2-Acetoxybenzoic acid;2-(Acetyloxy)benzoic acid;Acylpyrin;Aspirin;Aspirin granular',
  'Acetylsalicylic acid for peak identification, European Pharmacopoeia (EP) Reference Standard',
  'InChI=1/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12',
  '11126-35-5',
  'Aspirin (Acetyl Salicylic Acid), Pharmaceutical Secondary Standard; Certified Reference Material'],
 'chembl_id': 'CHEMBL25',
 'smiles': 'CC(=O)Oc1ccccc1C(=O)O',
 'inchikey': 'BSYNRYMUTXBXSQ-UHFFFAOYSA-N',
 'pubchem_cid': '2244',
 'rec_id': 'REC-0001392',
 'dose': None}

In [11]:
compound1 == compound2 == compound3

True

In [12]:
from explain.utils.entity import DiseaseEntity

In [13]:
disease_entity = await DiseaseEntity.from_id("MONDO:0005148")

In [14]:
disease_entity2 = await DiseaseEntity.from_id("D003924")

In [15]:
disease_entity == disease_entity2

True

### Investigation of cell context

In [ ]:
from google.cloud import bigquery

client = bigquery.Client(project="datalake-prod-ef49c0c9")

cell_t_list = [
    'iPSC-CORTICAL-ASTROCYTE','hMSC','HRCE','NHBE','HUVEC_BMP9','NHCE','A549','Other',
    'HUVEC_SF','SHSY5Y','AU565','RPEAd','BxPC3','HAEC','HEPARG','PTEC','iPSC-NGN2-NEURON',
    'LX-2','NHEK','SkMM','iCELL-CARDIOMYOCYTE','ASTROCYTE','PASMC','HACAT','AC16','NHCF',
    'VERO','CACO2','HUVEC_TNFa','ARPE19','FIBROBLAST','HEPG2','HUVEC','HUVEC_TNFalpha',
    'MACROPHAGE','MCF7','NHDF','NHLF','PBMC','RPE','RPTEC','U2OS','HMVECc'
]

query = """
SELECT
  cc.rec_id,
  ec.synonyms,
  ec.type,
  ec.fuzzy_representation,
  ctc.label AS cell_type,
  tc.label  AS tissue,
  sc.label  AS species,
  cc.culture_type,
  cc.disease,
  cc.vendor,
  cc.vendor_identifier,
  cc.vendor_lot,
  ec.tags,
  cc.created_at,
  cc.updated_at
FROM `cauldron__cauldron.cells`       AS cc
JOIN `cauldron__cauldron.entities`    AS ec ON ec.rec_id     = cc.rec_id
JOIN `cauldron__cauldron.cell_types`  AS ctc ON ctc.id       = cc.cell_type_id
JOIN `cauldron__cauldron.tissues`     AS tc  ON tc.id        = cc.tissue_id
JOIN `cauldron__cauldron.species`     AS sc  ON sc.id        = cc.species_id
WHERE EXISTS (
  SELECT 1
  FROM UNNEST(IFNULL(ec.synonyms, [])) AS s
  JOIN UNNEST(@terms) AS t
  ON STRPOS(LOWER(s), LOWER(t)) > 0
)
"""

job = client.query(
    query,
    job_config=bigquery.QueryJobConfig(
        query_parameters=[bigquery.ArrayQueryParameter("terms", "STRING", cell_t_list)]
    ),
)

df = job.result().to_dataframe()
df.head()

/Users/emmanuel.noutahi/Code/hooke-explain/.venv/lib/python3.12/site-packages/google/cloud/bigquery/table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,rec_id,synonyms,type,fuzzy_representation,cell_type,tissue,species,culture_type,disease,vendor,vendor_identifier,vendor_lot,tags,created_at,updated_at
0,REC-CELL-00135,[HUVEC_BMP9],CELL,"'-00135':5A '00135':3A 'bmp9':7B 'cell':2A,4A,...",DEFAULT,DEFAULT,DEFAULT,PRIMARY,Normal,None,None,None,[],2022-03-15 20:17:35.684100+00:00,2022-03-15 20:17:35.684100+00:00
1,REC-CELL-00136,[HUVEC_TNFalpha],CELL,"'-00136':5A '00136':3A 'cell':2A,4A,8C 'huvec'...",DEFAULT,DEFAULT,DEFAULT,PRIMARY,Normal,None,None,None,[],2022-03-15 20:20:19.528773+00:00,2022-03-15 20:20:19.528773+00:00
2,REC-CELL-00137,[iPSC-NGN2-NEURON],CELL,"'-00137':5A '00137':3A 'cell':2A,4A,10C 'ipsc'...",DEFAULT,DEFAULT,DEFAULT,PRIMARY,Normal,None,None,None,[],2022-04-08 19:32:29.443893+00:00,2022-04-08 19:32:29.443893+00:00
3,REC-CELL-00004,[A549],CELL,"'-00004':5A '00004':3A 'a549':6B 'cell':2A,4A,...",DEFAULT,DEFAULT,DEFAULT,LINE,Normal,None,None,None,[],2021-10-28 17:02:34.085753+00:00,2021-10-28 17:02:34.989116+00:00
4,REC-CELL-00005,[AC16],CELL,"'-00005':5A '00005':3A 'ac16':6B 'cell':2A,4A,...",DEFAULT,DEFAULT,DEFAULT,LINE,Normal,None,None,None,[],2021-10-28 17:02:57.116061+00:00,2021-10-28 17:02:57.997737+00:00

In [ ]:
df[["synonyms", "fuzzy_representation", "culture_type"]].to_json(orient="records")

'[{"synonyms":["HUVEC_BMP9"],"fuzzy_representation":"\'-00135\':5A \'00135\':3A \'bmp9\':7B \'cell\':2A,4A,8C \'huvec\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["HUVEC_TNFalpha"],"fuzzy_representation":"\'-00136\':5A \'00136\':3A \'cell\':2A,4A,8C \'huvec\':6B \'rec\':1A \'tnfalpha\':7B","culture_type":"PRIMARY"},{"synonyms":["iPSC-NGN2-NEURON"],"fuzzy_representation":"\'-00137\':5A \'00137\':3A \'cell\':2A,4A,10C \'ipsc\':7B \'ipsc-ngn2-neuron\':6B \'neuron\':9B \'ngn2\':8B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["A549"],"fuzzy_representation":"\'-00004\':5A \'00004\':3A \'a549\':6B \'cell\':2A,4A,7C \'rec\':1A","culture_type":"LINE"},{"synonyms":["AC16"],"fuzzy_representation":"\'-00005\':5A \'00005\':3A \'ac16\':6B \'cell\':2A,4A,7C \'rec\':1A","culture_type":"LINE"},{"synonyms":["ARPE19"],"fuzzy_representation":"\'-00006\':5A \'00006\':3A \'arpe19\':6B \'cell\':2A,4A,7C \'rec\':1A","culture_type":"LINE"},{"synonyms":["iPSC-ASTROCYTE"],"fuzzy_representation":"\'-00007\':5A \'00007\':3A \'astrocyte\':8B \'cell\':2A,4A,9C \'ipsc\':7B \'ipsc-astrocyte\':6B \'rec\':1A","culture_type":"IPSC"},{"synonyms":["AU565"],"fuzzy_representation":"\'-00008\':5A \'00008\':3A \'au565\':6B \'cell\':2A,4A,7C \'rec\':1A","culture_type":"LINE"},{"synonyms":["BxPC3"],"fuzzy_representation":"\'-00009\':5A \'00009\':3A \'bxpc3\':6B \'cell\':2A,4A,7C \'rec\':1A","culture_type":"LINE"},{"synonyms":["CACO2"],"fuzzy_representation":"\'-00010\':5A \'00010\':3A \'caco2\':6B \'cell\':2A,4A,7C \'rec\':1A","culture_type":"LINE"},{"synonyms":["HACAT"],"fuzzy_representation":"\'-00012\':5A \'00012\':3A \'cell\':2A,4A,7C \'hacat\':6B \'rec\':1A","culture_type":"LINE"},{"synonyms":["HAEC"],"fuzzy_representation":"\'-00013\':5A \'00013\':3A \'cell\':2A,4A,7C \'haec\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["HEPARG"],"fuzzy_representation":"\'-00016\':5A \'00016\':3A \'cell\':2A,4A,7C \'heparg\':6B \'rec\':1A","culture_type":"LINE"},{"synonyms":["HEPG2"],"fuzzy_representation":"\'-00017\':5A \'00017\':3A \'cell\':2A,4A,7C \'hepg2\':6B \'rec\':1A","culture_type":"LINE"},{"synonyms":["hMSC"],"fuzzy_representation":"\'-00018\':5A \'00018\':3A \'cell\':2A,4A,7C \'hmsc\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["HRCE"],"fuzzy_representation":"\'-00021\':5A \'00021\':3A \'cell\':2A,4A,7C \'hrce\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["HUVEC"],"fuzzy_representation":"\'-00022\':5A \'00022\':3A \'cell\':2A,4A,7C \'huvec\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["iCELL-CARDIOMYOCYTE"],"fuzzy_representation":"\'-00023\':5A \'00023\':3A \'cardiomyocyte\':8B \'cell\':2A,4A,9C \'icell\':7B \'icell-cardiomyocyte\':6B \'rec\':1A","culture_type":"IPSC"},{"synonyms":["iPSC-CORTICAL-ASTROCYTE"],"fuzzy_representation":"\'-00024\':5A \'00024\':3A \'astrocyte\':9B \'cell\':2A,4A,10C \'cortical\':8B \'ipsc\':7B \'ipsc-cortical-astrocyte\':6B \'rec\':1A","culture_type":"IPSC"},{"synonyms":["MACROPHAGE"],"fuzzy_representation":"\'-00028\':5A \'00028\':3A \'cell\':2A,4A,7C \'macrophage\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["MCF7"],"fuzzy_representation":"\'-00029\':5A \'00029\':3A \'cell\':2A,4A,7C \'mcf7\':6B \'rec\':1A","culture_type":"LINE"},{"synonyms":["NHBE"],"fuzzy_representation":"\'-00032\':5A \'00032\':3A \'cell\':2A,4A,7C \'nhbe\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["NHCF"],"fuzzy_representation":"\'-00033\':5A \'00033\':3A \'cell\':2A,4A,7C \'nhcf\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["NHDF"],"fuzzy_representation":"\'-00034\':5A \'00034\':3A \'cell\':2A,4A,7C \'nhdf\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["NHEK"],"fuzzy_representation":"\'-00035\':5A \'00035\':3A \'cell\':2A,4A,7C \'nhek\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["NHLF"],"fuzzy_representation":"\'-00036\':5A \'00036\':3A \'cell\':2A,4A,7C \'nhlf\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["PASMC"],"fuzzy_representation":"\'-00037\':5A \'00037\':3A \'cell\':2A,4A,7C \'pasmc\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["PBMC"],"fuzzy_representation":"\'-00038\':5A \'00038\':3A \'cell\':2A,4A,7C \'pbmc\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["PTEC"],"fuzzy_representation":"\'-00039\':5A \'00039\':3A \'cell\':2A,4A,7C \'ptec\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["SHSY5Y"],"fuzzy_representation":"\'-00040\':5A \'00040\':3A \'cell\':2A,4A,7C \'rec\':1A \'shsy5y\':6B","culture_type":"LINE"},{"synonyms":["SkMM"],"fuzzy_representation":"\'-00041\':5A \'00041\':3A \'cell\':2A,4A,7C \'rec\':1A \'skmm\':6B","culture_type":"PRIMARY"},{"synonyms":["U2OS"],"fuzzy_representation":"\'-00042\':5A \'00042\':3A \'cell\':2A,4A,7C \'rec\':1A \'u2os\':6B","culture_type":"LINE"},{"synonyms":["VERO"],"fuzzy_representation":"\'-00043\':5A \'00043\':3A \'cell\':2A,4A,7C \'rec\':1A \'vero\':6B","culture_type":"LINE"},{"synonyms":["VEROE6"],"fuzzy_representation":"\'-00044\':5A \'00044\':3A \'cell\':2A,4A,7C \'rec\':1A \'veroe6\':6B","culture_type":"LINE"},{"synonyms":["FIBROBLAST"],"fuzzy_representation":"\'-00112\':5A \'00112\':3A \'cell\':2A,4A,7C \'fibroblast\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["ASTROCYTE"],"fuzzy_representation":"\'-00110\':5A \'00110\':3A \'astrocyte\':6B \'cell\':2A,4A,7C \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["IMHUVEC"],"fuzzy_representation":"\'-00115\':5A \'00115\':3A \'cell\':2A,4A,7C \'imhuvec\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["Other"],"fuzzy_representation":"\'-00122\':5A \'00122\':3A \'cell\':2A,4A,7C \'other\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["RPE"],"fuzzy_representation":"\'-00120\':5A \'00120\':3A \'cell\':2A,4A,7C \'rec\':1A \'rpe\':6B","culture_type":"PRIMARY"},{"synonyms":["NHCE"],"fuzzy_representation":"\'-00119\':5A \'00119\':3A \'cell\':2A,4A,7C \'nhce\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["HMVECc"],"fuzzy_representation":"\'-00113\':5A \'00113\':3A \'cell\':2A,4A,7C \'hmvecc\':6B \'rec\':1A","culture_type":"PRIMARY"},{"synonyms":["HUVEC_SF"],"fuzzy_representation":"\'-00134\':5A \'00134\':3A \'cell\':2A,4A,8C \'huvec\':6B \'rec\':1A \'sf\':7B","culture_type":"PRIMARY"},{"synonyms":["LX-2"],"fuzzy_representation":"\'-00150\':5A \'-2\':7B \'00150\':3A \'cell\':2A,4A,8C \'lx\':6B \'rec\':1A","culture_type":"LINE"},{"synonyms":["RPTEC"],"fuzzy_representation":"\'-00153\':5A \'00153\':3A \'cell\':2A,4A,7C \'rec\':1A \'rptec\':6B","culture_type":"PRIMARY"}]'

In [ ]:
from explain.utils.entity import CellContext

In [ ]:
context = await CellContext.from_name("A549")
context

2025-09-03 10:47:34.243 | INFO     | explain.utils.entity:update:30 - Updated cell type CVCL_IY87 from KG

CellContext(id='CVCL_IY87', name='A549/8', synonyms=[], cell_type='CulturedCell', culture_type=None, description='\\Population: Caucasian. Selected for resistance to: ChEBI; CHEBI:9555; Tioguanine (6-thioguanine. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Derived from sampling site: Lung.\\""', sex='<https://www.exscientia.ai/cb_schema#male>', origin_type='cancer', derived_tissue=None)

In [ ]:
import pandas as pd

tmp = pd.read_csv("~/Downloads/gene_attribute_matrix.txt", sep="\t")
import numpy as np
np.random.choice([x for x in tmp.columns if 'Human' in x], 50)

array(['Plasmacytoid dendritic cell(pDC)_Uterus_Human',
       'T follicular helper(Tfh) cell_Skin_Human',
       'Activated effector memory CD8+ T cell_Airway_Human',
       'Natural killer cell_Skin_Human',
       'Innate lymphoid cell_Tonsil_Human',
       'Gamma delta(γδ) T cell_Blood_Human',
       'Immune suppressive macrophage_Brain_Human',
       'Lymphocyte_Endometrium_Human',
       'Plasmacytoid dendritic cell_Kidney_Human',
       'Effector T(Teff) cell_Kidney_Human',
       'Follicular B cell_Undefined_Human',
       'Intermediate monocyte_Blood_Human',
       'Mesoderm cell_Calvaria_Human',
       'T follicular helper(Tfh) cell_Lymph node_Human',
       'T helper(Th) cell_Peripheral blood_Human',
       'Goblet progenitor cell_Large intestine_Human',
       'Early erythrocyte_Fetal liver_Human',
       'Non-malignant epithelial cell_Undefined_Human',
       'Germ cell_Ovary_Human', 'Neural tube cell_Germ_Human',
       'Terminal differentiated B cell_Blood_Human',
       'Central memory CD4+ T cell_Undefined_Human',
       'Terminal differentiated B cell_Blood_Human',
       'Adult stem cell_Intestine_Human',
       'Smooth muscle cell_Lymphoid tissue_Human',
       'Multipotent mesenchymal stroma cell_Bone marrow_Human',
       'Monocyte_Lung_Human', 'Transitional B cell_Bone marrow_Human',
       'Hematopoietic stem cell_Blood_Human',
       'Cancer stem cell_Lymph_Human',
       'Nonhematopoietic heteroploid cell_Blood_Human',
       'Adipocyte_Stomach_Human',
       'Endothelial progenitor cell_Umbilical cord blood_Human',
       'Neutrophil_Bronchoalveolar lavage_Human',
       'Central memory CD4+ T cell_Spleen_Human',
       'Mesodermal embryonic stem cell_Germ_Human',
       'Hematopoietic stem cell_Umbilical cord blood_Human',
       'CD14+ monocyte-derived macrophage_Anogenital tract_Human',
       'Fibroblast_Spleen_Human',
       'Adipose-derived stem cell_Visceral adipose tissue_Human',
       'Myofibroblast_Liver_Human',
       'Epithelial progenitor cell_Kidney_Human',
       'Immune cell_Blood vessel_Human',
       'Epithelial cell_Endometrium stroma_Human',
       'Activated hepatic stellate cell_Liver_Human',
       'Oxyntic progenitor cell_Stomach_Human', 'B cell_Lymph_Human',
       'T cell_Choroid_Human', 'Schwann cell_Choroid_Human',
       'M0 macrophage_Kidney_Human'], dtype='<U98')

In [ ]:
tmp = pd.read_csv("~/Downloads/PanglaoDB_markers_27_Mar_2020.tsv", sep="\t")
#tmp["cell type"].unique()

In [ ]:
await client.get_cellular_context_info("A549")

{'results': [{'id': 'CVCL_IY87',
   'name': 'A549/8',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Selected for resistance to: ChEBI; CHEBI:9555; Tioguanine (6-thioguanine. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_4V06',
   'name': 'A549(VM)28',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Selected for resistance to: ChEBI; CHEBI:75988; Teniposide (VM-26). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_4V07',
   'name': 'A549(VP)28',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Selected for resistance to: ChEBI; CHEBI:4911; Etoposide (VP-16). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 2},
  {'id': 'CVCL_4Z15',
   'name': 'A549.EpoB40',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Selected for resistance to: ChEBI; CHEBI:31550; Epothilone B (EpoB). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Derived from sampling site: Lung.\\""',
   'synonyms': ['EpoB40'],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 3},
  {'id': 'CVCL_5I73',
   'name': 'A549-Dual',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Characteristics: Stably expresses two reporter genes: SEAP (secreted ALPP) and the Lucia luciferase. In this cell line SEAP is under the control of an IFN-beta minimal promoter fused to 5 NF-kappaB binding sites. The Lucia luciferase reporter gene is under the control of an ISG54 minimal promoter in conjunction with 5 IFN-stimulated response elements (ISRE). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 439; ALPP. Transfected with: Lucia luciferase, a synthetic gene designed on natural secreted luciferase genes from marine copepods. Transfected with: UniProtKB; P17493; Streptoalloteichus hindustanus ble (BleoR). Transfected with: UniProtKB; P33967; B.cereus Bsr. Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_5I86',
   'name': 'A549-Red-FLuc',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Doubling time: 22 hours (PerkinElmer). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: UniProtKB; Q1AG35; Italian firefly luciferase. Transfected with: UniProtKB; P13249; S.alboniger pac (PuroR). Derived from sampling site: Lung.\\""',
   'synonyms': ['A549 Red-FLuc', 'Bioware Brite A549 Red-FLuc'],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_5J13',
   'name': 'A549-luc-C8',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: UniProtKB; P08659; Firefly luciferase. Discontinued: PerkinElmer; 119266; true. Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 5},
  {'id': 'CVCL_5J44',
   'name': 'p53-RE-luc/A549',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: UniProtKB; P08659; Firefly luciferase. Discontinued: PerkinElmer; 119274; true. Derived from sampling site: Lung.\\""',
   'synonyms': ['P53-RE-luc/A549'],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A0VZ',
   'name': 'A549-CBG',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Characteristics: Transduced with a CBG-T2A-GFP construct. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: CBG, click beetle green luciferase. Transfected with: UniProtKB; P42212; GFP (with p.Phe64Leu, p.Ser65Thr and p.His231Leu = EGFP). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A0WA',
   'name': 'A549-A2-ESO',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Characteristics: Transduced with both a CBG-T2A-GFP construct and a NY-ESO-1-T2A-HLA-A2 construct. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 24198; CTAG1A. Transfected with: HGNC; 4931; HLA-A (allele A*2). Transfected with: CBG, click beetle green luciferase. Transfected with: UniProtKB; P42212; GFP (with p.Phe64Leu, p.Ser65Thr and p.His231Leu = EGFP). Derived from sampling site: Lung.\\""',
   'synonyms': ['A549-NY-ESO-1-A2-CBG'],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A1ZW',
   'name': 'A549-1',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Characteristics: Selected to grow at low density. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A1ZX',
   'name': 'A549-R0',
   'cell_type': 'CulturedCell',
   'description': '\\Group: Serum/protein free medium cell line. Population: Caucasian. Doubling time: 8-10 days (PubMed=8132585). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A5KA',
   'name': 'A549-hACE2 [Invivogen]',
   'cell_type': 'CulturedCell',
   'description': '\\Group: SARS-CoV-2 research cell line. Population: Caucasian. Characteristics: Permissive to infection by SARS-CoV-2 and/or spike-pseudotyped lentiviral particles (InvivoGen). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 13557; ACE2. Transfected with: UniProtKB; P13249; S.alboniger pac (PuroR). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A5KB',
   'name': 'A549-hACE2-TMPRSS2',
   'cell_type': 'CulturedCell',
   'description': '\\Group: SARS-CoV-2 research cell line. Population: Caucasian. Virology: Highly susceptible to infection by SARS coronavirus 2 (SARS-CoV-2) (COVID-19) and/or spike-pseudotyped lentiviral particles (InvivoGen). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 13557; ACE2. Transfected with: HGNC; 11876; TMPRSS2. Transfected with: UniProtKB; P00557; Escherichia coli hygromycin-B 4-O-kinase (hph). Transfected with: UniProtKB; P13249; S.alboniger pac (PuroR). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A7UV',
   'name': 'A549-hACE2 [BEI resources]',
   'cell_type': 'CulturedCell',
   'description': '\\Group: SARS-CoV-2 research cell line. From: Baric R.; Department of Epidemiology, University of North Carolina at Chapel Hill; Chapel Hill; USA. Population: Caucasian. Characteristics: Expresses ACE2 under the control of the EF1a promoter (BEI_Resources). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 13557; ACE2. Transfected with: UniProtKB; P0C2P0; Aspergillus terreus blasticidin-S deaminase (Bsd). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A7UW',
   'name': 'A549-hACE2 (HA-FLAG)',
   'cell_type': 'CulturedCell',
   'description': '\\Group: SARS-CoV-2 research cell line. From: Garcia-Sastre A.; The Icahn School of Medicine at Mount Sinai Medical School; New York; USA. Population: Caucasian. Characteristics: Expresses ACE2 with C-terminal HA and FLAG tags under the control the CMV promoter (BEI_Resources). Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 13557; ACE2. Transfected with: UniProtKB; P13249; S.alboniger pac (PuroR). Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A7ZM',
   'name': 'A549-Dual KO-MAVS',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Characteristics: Stably expresses two reporter genes: SEAP (secreted ALPP) and the Lucia luciferase. In this cell line SEAP is under the control of an IFN-beta minimal promoter fused to 5 NF-kappaB binding sites. The Lucia luciferase reporter gene is under the control of an ISG54 minimal promoter in conjunction with 5 IFN-stimulated response elements (ISRE). Knockout cell: Method=Not specified; HGNC; 29233; MAVS. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 439; ALPP. Transfected with: Lucia luciferase, a synthetic gene designed on natural secreted luciferase genes from marine copepods. Transfected with: UniProtKB; P17493; Streptoalloteichus hindustanus ble (BleoR). Transfected with: UniProtKB; P33967; B.cereus Bsr. Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A7ZN',
   'name': 'A549-Dual KO-RIG-I',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Characteristics: Stably expresses two reporter genes: SEAP (secreted ALPP) and the Lucia luciferase. In this cell line SEAP is under the control of an IFN-beta minimal promoter fused to 5 NF-kappaB binding sites. The Lucia luciferase reporter gene is under the control of an ISG54 minimal promoter in conjunction with 5 IFN-stimulated response elements (ISRE). Knockout cell: Method=Not specified; HGNC; 19102; RIGI. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 439; ALPP. Transfected with: Lucia luciferase, a synthetic gene designed on natural secreted luciferase genes from marine copepods. Transfected with: UniProtKB; P17493; Streptoalloteichus hindustanus ble (BleoR). Transfected with: UniProtKB; P33967; B.cereus Bsr. Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A7ZP',
   'name': 'A549-Dual KO-MDA5',
   'cell_type': 'CulturedCell',
   'description': '\\Population: Caucasian. Characteristics: Stably expresses two reporter genes: SEAP (secreted ALPP) and the Lucia luciferase. In this cell line SEAP is under the control of an IFN-beta minimal promoter fused to 5 NF-kappaB binding sites. The Lucia luciferase reporter gene is under the control of an ISG54 minimal promoter in conjunction with 5 IFN-stimulated response elements (ISRE). Knockout cell: Method=Not specified; HGNC; 18873; IFIH1. Sequence variation: Mutation; HGNC; 6407; KRAS; Simple; p.Gly12Ser (c.34G>A); ClinVar=VCV000012584; Zygosity=Homozygous (from parent cell line). Sequence variation: Mutation; HGNC; 11389; STK11; Simple; p.Gln37Ter (c.109C>T); ClinVar=VCV000376334; Zygosity=Homozygous (from parent cell line). Transfected with: HGNC; 439; ALPP. Transfected with: Lucia luciferase, a synthetic gene designed on natural secreted luciferase genes from marine copepods. Transfected with: UniProtKB; P17493; Streptoalloteichus hindustanus ble (BleoR). Transfected with: UniProtKB; P33967; B.cereus Bsr. Derived from sampling site: Lung.\\""',
   'synonyms': [],
   'sex': '<https://www.exscientia.ai/cb_schema#male>',
   'origin_type': 'cancer',
   'derived_tissue': '',
   'native_cell_name': '',
   'native_cell_description': '',
   'publication_count': 0},
  {'id': 'CVCL_A7ZQ',
   'name': 'A549-Dual hACE2-TMPRSS2',
   'cell_type': 'CulturedCell',