In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import re
from explain.eval.tools.bio.localization import SCLArgs, SCLVerifier

/rxrx/data/user/lu.zhu/hooke-explain/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-08-12 19:35:43.101 | INFO     | explain.llm._client:__init__:472 - Initialized OpenAI client with model gpt-4.1
2025-08-12 19:35:43.102 | INFO     | explain.llm._client:__init__:694 - Initialized unified LLM client with provider: openai

### Load explain example

In [2]:
TEST_DATA_PATH = (
    "/mnt/ps/home/CORP/lu.zhu/project/hooke-explain/data/curation_v1/results/structure-explain-results-v3-gemini2-5.csv"
)

data = pd.read_csv(TEST_DATA_PATH)

In [3]:
scl_rows = [expl for row in data["explain"] for expl in row.split("\n") if "localises_to" in expl]
scl_rows

['  localises_to(id="n5", entity="STAT6", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="decreased phosphorylation and dimerization")',
 '  localises_to(id="n6", entity="STAT1/STAT3/STAT6", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation")',
 '  localises_to(id="n5", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation and dimerization", confidence="high")',
 '  localises_to(id="n6", entity="STAT6", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced phosphorylation and dimerization")',
 '  localises_to(id="n7", entity="STAT6 dimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced STAT6 phosphorylation")',
 '  localises_to(id="n4", entity="STAT6", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="prevention of dimerization and nuclear translocation due to reduced phosphorylation", confidence="high")',
 '  localises_to(id="n5", entity="STAT6", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired phosphorylation and dimerization")',
 '  localises_to(id="n4", entity="STAT6", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced phosphorylation")',
 '  localises_to(id="n5", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", via="phosphorylation and dimerization")',
 '  localises_to(id="n11", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation and dimerization")',
 '  localises_to(id="n4", entity="STAT1/3/6", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired dimerization due to lack of phosphorylation")',
 '  localises_to(id="n4", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation and dimerization")',
 '  localises_to(id="n9", entity="STAT6 dimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced STAT6 phosphorylation and dimerization")',
 '  localises_to(id="n5", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation and dimerization", confidence="high")',
 '  localises_to(id="n9", entity="STAT dimers", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="prevention of phosphorylation and dimerization")',
 '  localises_to(id="n5", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation and dimerization", confidence="high")',
 '  localises_to(id="n4", entity="phosphorylated Smad2/3", from_loc="cytoplasm", to_loc="nucleus", via="phosphorylation-induced nuclear translocation")',
 '  localises_to(id="n10", entity="Smad2/3", from_loc="nucleus", to_loc="cytoplasm", via="reduced phosphorylation preventing nuclear translocation")',
 '  localises_to(id="n4", entity="SMAD2/3 complex", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced phosphorylation")',
 '  localises_to(id="n4", entity="phosphorylated SMAD2/3", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced phosphorylation")',
 '  localises_to(id="n15", entity="FOXO", from_loc="cytoplasm", to_loc="nucleus", via="FOXO re-activation")',
 '  localises_to(id="n4", entity="AKT", from_loc="cytoplasm", to_loc="plasma membrane", via="PIP3 accumulation")',
 '  localises_to(id="n12", entity="AKT", from_loc="plasma membrane", to_loc="cytoplasm", via="reduced PIP3 levels")',
 '  localises_to(id="n7", entity="FOXO", from_loc="cytoplasm", to_loc="nucleus", via="reduced AKT-mediated phosphorylation")',
 '  localises_to(id="n4", entity="AKT", from_loc="cytosol", to_loc="plasma membrane", direction="down", via="reduced PIP3 levels", confidence="high")',
 '  localises_to(id="n9", entity="FOXO", from_loc="cytoplasm", to_loc="nucleus", via="reduced AKT-mediated phosphorylation")',
 '  localises_to(id="n7", entity="Smad complex", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced Smad complex formation")',
 '  localises_to(id="n5", entity="SMAD2/3-SMAD4 complex", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced complex formation")',
 '  localises_to(id="n4", entity="SMAD2/3/4 complex", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced SMAD2/3 phosphorylation")',
 '  localises_to(id="n4", entity="Smad2/3-Smad4 complex", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="n3")',
 '  localises_to(id="n5", entity="SMAD complex", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced SMAD complex formation", confidence="high")',
 '  localises_to(id="n4", entity="β-catenin", from_loc="cytoplasm", to_loc="nucleus", via="impaired degradation and stabilization")',
 '  localises_to(id="n3", entity="beta-catenin", from_loc="cytoplasm", to_loc="nucleus", via="accumulation")',
 '  localises_to(id="n5", entity="beta-catenin", from_loc="cytoplasm", to_loc="nucleus", via="cytoplasmic accumulation and stabilization")',
 '  localises_to(id="n5", entity="CTNNB1", from_loc="cytoplasm", to_loc="nucleus", via="increased cytoplasmic concentration")',
 '  localises_to(id="n3", entity="β-catenin", from_loc="cytoplasm", to_loc="nucleus", via="cytoplasmic accumulation")',
 '  localises_to(id="n5", entity="β-catenin", from_loc="cytoplasm", to_loc="nucleus", via="cytoplasmic accumulation")',
 '  localises_to(id="n21", entity="β-catenin", from_loc="nucleus", to_loc="membrane", via="attenuated Wnt signaling and restored GSK3β function")',
 '  localises_to(id="n8", entity="β-catenin", from_loc="cytoplasm", to_loc="nucleus", via="enhanced cytoplasmic accumulation")',
 '  localises_to(id="n4", entity="phosphorylated STAT dimers", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="decreased phosphorylation")',
 '  localises_to(id="n6", entity="STAT3", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced phosphorylation")',
 '  localises_to(id="n4", entity="STAT3", from_loc="cytoplasm", to_loc="nucleus", via="STAT3 phosphorylation")',
 '  localises_to(id="n12", entity="STAT3", from_loc="nucleus", to_loc="cytoplasm", via="reduced STAT3 phosphorylation")',
 '  localises_to(id="n4", entity="phosphorylated STAT3", from_loc="cytoplasm", to_loc="nucleus", via="STAT3 phosphorylation")',
 '  localises_to(id="n10", entity="phosphorylated STATs", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced STAT phosphorylation")',
 '  localises_to(id="n4", entity="pSTAT3", to_loc="nucleus", direction="up", via="increased phosphorylation and dimerization", confidence="causal")',
 '  localises_to(id="n10", entity="pSTAT3", to_loc="nucleus", direction="down", via="reduced phosphorylation", confidence="causal")',
 '  localises_to(id="n6", entity="STAT3", from_loc="cytoplasm", to_loc="nucleus", direction="up", via="phosphorylation-induced nuclear translocation")',
 '  localises_to(id="n17", entity="STAT3", from_loc="nucleus", to_loc="cytoplasm", direction="down", via="reduced phosphorylation-induced nuclear translocation")',
 '  localises_to(id="n3", entity="IFNAR1", from_loc="cell surface", to_loc="intracellular", mechanism="internalization", via="Anifrolumab binding")',
 '  localises_to(id="n3", entity="HIF-2α/ARNT heterodimer", from_loc="cytoplasm", to_loc="nucleus", via="functional heterodimer formation")',
 '  localises_to(id="n8", entity="EPAS1", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired HIF-2α/ARNT complex formation")',
 '  localises_to(id="n5", entity="NF-κB", from_loc="cytoplasm", to_loc="cytoplasm", via="stable IκB sequestration, blocking nuclear translocation")',
 '  localises_to(id="n5", entity="NF-κB complex", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="sequestration by NFKBIA")',
 '  localises_to(id="n5", entity="NF-κB", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="persistent IκBα binding", confidence="high")',
 '  localises_to(id="n5", entity="NF-κB", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="sequestration by IκBα")',
 '  localises_to(id="n5", entity="NF-κB dimers", from_loc="cytoplasm", to_loc="cytoplasm", via="IκB sequestration")',
 '  localises_to(id="n8", entity="ISGF3", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="inhibited ISGF3 complex formation")',
 '  localises_to(id="n7", entity="ISGF3", from_loc="cytoplasm", to_loc="nucleus", via="prevented by lack of ISGF3 complex formation", confidence="high")',
 '  localises_to(id="n8", entity="STAT1/2", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired ISGF3 complex formation")',
 '  localises_to(id="n10", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired phosphorylation and dimerization")',
 '  localises_to(id="n4", entity="AKT", from_loc="cytoplasm", to_loc="plasma membrane", direction="down", via="lack of PIP3 recruitment")',
 '  localises_to(id="n11", entity="NF-κB", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="continued sequestration by IκBα")',
 '  localises_to(id="n4", entity="AKT", from_loc="cytoplasm", to_loc="plasma membrane", direction="down", via="reduced PIP3 levels")',
 '  localises_to(id="n11", entity="NF-kappaB", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="n10")',
 '  localises_to(id="n4", entity="AKT", from_loc="cytosol", to_loc="plasma membrane", via="blocked PIP3 generation", confidence="high")',
 '  localises_to(id="n10", entity="NF-κB", from_loc="cytoplasm", to_loc="nucleus", via="increased cytoplasmic retention due to IκB stabilization", confidence="high")',
 '  localises_to(id="n6", entity="AKT", from_loc="cytosol", to_loc="membrane", direction="down", via="decreased PIP3 levels", confidence="high")',
 '  localises_to(id="n14", entity="NF-κB", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="IκB sequestration", confidence="high")',
 '  localises_to(id="n6", entity="NF-κB", from_loc="cytoplasm", to_loc="cytoplasm", mechanism="sequestration by IκBα", via="stabilised IκBα")',
 '  localises_to(id="n5", entity="NF-κB", from_loc="cytoplasm", to_loc="cytoplasm", via="sequestration by stable IκBα")',
 '  localises_to(id="n5", entity="NF-κB", from_loc="nucleus", to_loc="cytoplasm", direction="down", via="sequestration by stabilized IκB-α in the cytoplasm")',
 '  localises_to(id="n5", entity="NF-κB dimers", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="IκBα sequestration")',
 '  localises_to(id="n5", entity="NF-κB", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="IκB cytoplasmic retention")',
 '  localises_to(id="n7", entity="STAT1", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="inhibited phosphorylation and dimerization")',
 '  localises_to(id="n8", entity="STAT3", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="inhibited phosphorylation and dimerization")',
 '  localises_to(id="n9", entity="STAT proteins", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation and dimerization")',
 '  localises_to(id="n5", entity="STAT1, STAT3", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="inhibition of STAT phosphorylation")',
 '  localises_to(id="n4", entity="STAT1/STAT3", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="inhibited phosphorylation and dimerization", confidence="high")',
 '  localises_to(id="n8", entity="STAT1 dimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced STAT1 dimerization")',
 '  localises_to(id="n5", entity="STAT1 homodimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired dimerization")',
 '  localises_to(id="n4", entity="STAT1 homodimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced phosphorylation and impaired dimerization", confidence="high")',
 '  localises_to(id="n5", entity="STAT1 homodimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired dimerization")',
 '  localises_to(id="n5", entity="STAT1", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="prevented STAT1 dimerization", confidence="high")',
 '  localises_to(id="n9", entity="STAT1 homodimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="prevention of dimerization")',
 '  localises_to(id="n4", entity="STAT", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of phosphorylation and dimerization")',
 '  localises_to(id="n4", entity="STAT1", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired phosphorylation and dimerization")',
 '  localises_to(id="n5", entity="STAT1 dimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="lack of dimerization")',
 '  localises_to(id="n6", entity="STAT1 homodimer", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="impaired dimerization")',
 '  localises_to(id="n4", entity="STAT1", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="reduced phosphorylation and dimer formation")',
 '  localises_to(id="n7", entity="STAT1", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="inhibited STAT1 phosphorylation and dimerization", confidence="high")',
 '  localises_to(id="n4", entity="STAT1", from_loc="cytoplasm", to_loc="nucleus", direction="down", via="inability to dimerize due to lack of phosphorylation")']

In [4]:
data

,index,question,thinking,answer,explain,dag,raw_response,success,error,input_perturbation,input_report_text
0,0,How does the following perturbation influence ...,The task is to explain the mechanism of action...,"Bevacizumab, a recombinant humanized monoclona...","set_context(id=""n0"", cell_type=""endothelial ce...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe task is to explain the mechanism ...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,# Comprehensive Mechanistic Report: Bevacizuma...
1,1,How does the following perturbation influence ...,1. **Context Understanding**: The initial con...,Nintedanib is a multi-tyrosine kinase inhibito...,"set_context(id=""n0"", cell_type=""endothelial ce...","edge(""n0"", ""n1"", relation=""causal"")\nedge(""n1""...",<think>\n1. **Context Understanding**: The in...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Report: Nintedanib's Inhibitor...
2,2,How does the following perturbation influence ...,The user wants a structured explanation of Apa...,Apatinib is a small-molecule tyrosine kinase i...,"set_context(id=""n0"", cell_type=""vascular endot...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe user wants a structured explanati...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Report: Apatinib in VEGF-Media...
3,3,How does the following perturbation influence ...,The task is to explain the mechanism of action...,Lenvatinib is a multi-targeted tyrosine kinase...,"set_context(id=""n0"", cell_type=""vascular endot...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe task is to explain the mechanism ...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Report: Impact of Lenvatinib o...
4,4,How does the following perturbation influence ...,The user wants to understand the mechanism of ...,"Motesanib, a multi-targeted tyrosine kinase in...","set_context(id=""n0"", cell_type=""endothelial ce...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe user wants to understand the mech...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,# Motesanib: A Multi-Targeted Tyrosine Kinase ...
...,...,...,...,...,...,...,...,...,...,...,...
171,171,How does the following perturbation influence ...,The user wants to understand the mechanism of ...,"Solcitinib, an ATP-competitive inhibitor, bind...","set_context(id=""n0"", disease=""inflammatory dis...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe user wants to understand the mech...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Report: Solcitinib's Impact on...
172,172,How does the following perturbation influence ...,The task is to explain the mechanism of action...,TG 101209 is an ATP-competitive inhibitor that...,"set_context(id=""n0"", cell_type=""immune cells"",...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe task is to explain the mechanism ...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Analysis of TG 101209 in IFN-g...
173,173,How does the following perturbation influence ...,The task is to explain the mechanism of action...,"TG 101348, an ATP-competitive inhibitor, prima...","set_context(id=""n0"", cell_type=""immune cells"",...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe task is to explain the mechanism ...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Analysis of TG 101348 in IFNγ-...
174,174,How does the following perturbation influence ...,The user wants to understand the mechanism of ...,AZ 960 is a potent and selective ATP-competiti...,"set_context(id=""n0"", cell_type=""various"", dise...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n3""...",<think>\nThe user wants to understand the mech...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Report: Impact of AZ 960 on IF...
175,175,How does the following perturbation influence ...,The user wants to understand the mechanism of ...,CEP 33779 is a small molecule inhibitor that a...,"set_context(id=""n0"", cell_type=""various"", dise...","edge(""n1"", ""n2"", relation=""causal"")\nedge(""n2""...",<think>\nThe user wants to understand the mech...,True,NaN,{'context': {'perturbation_type': 'soluble fac...,\n# Mechanistic Report: Impact of CEP 33779 on...

In [5]:
scl_rows = [
    (pert, expl)
    for i, (pert, row) in data[["input_perturbation", "explain"]].iterrows()
    for expl in row.split("\n")
    if "localises_to" in expl
]

# extract the scl info from explain
scl_data = []
for pert, expl in scl_rows:
    entity = re.search(r'entity\s*=\s*["\']([^"\']+)["\']', expl).group(1)
    from_loc = re.search(r'from_loc\s*=\s*["\']([^"\']+)["\']', expl)
    if from_loc:
        from_loc = from_loc.group(1).strip()
    to_loc = re.search(r'to_loc\s*=\s*["\']([^"\']+)["\']', expl).group(1)
    mechanism = re.search(r'mechanism\s*=\s*["\']([^"\']*)["\']', expl)
    if mechanism:
        mechanism = mechanism.group(1).strip()
    modification = re.search(r'via\s*=\s*["\']([^"\']+)["\']', expl)
    if modification:
        modification = modification.group(1).strip()
    scl_data.append([pert, entity, from_loc, to_loc, mechanism, modification])

scl_data = pd.DataFrame(scl_data, columns=["perturbation", "entity", "from_loc", "to_loc", "mechanism", "modification"])

In [6]:
scl_data = scl_data.drop_duplicates(subset=["entity", "from_loc", "to_loc"])
scl_data

,perturbation,entity,from_loc,to_loc,mechanism,modification
0,{'context': {'perturbation_type': 'soluble fac...,STAT6,cytoplasm,nucleus,None,decreased phosphorylation and dimerization
1,{'context': {'perturbation_type': 'soluble fac...,STAT1/STAT3/STAT6,cytoplasm,nucleus,None,lack of phosphorylation
2,{'context': {'perturbation_type': 'soluble fac...,STAT proteins,cytoplasm,nucleus,None,lack of phosphorylation and dimerization
4,{'context': {'perturbation_type': 'soluble fac...,STAT6 dimer,cytoplasm,nucleus,None,reduced STAT6 phosphorylation
10,{'context': {'perturbation_type': 'soluble fac...,STAT1/3/6,cytoplasm,nucleus,None,impaired dimerization due to lack of phosphory...
14,{'context': {'perturbation_type': 'soluble fac...,STAT dimers,cytoplasm,nucleus,None,prevention of phosphorylation and dimerization
16,{'context': {'perturbation_type': 'loss-of-fun...,phosphorylated Smad2/3,cytoplasm,nucleus,None,phosphorylation-induced nuclear translocation
17,{'context': {'perturbation_type': 'loss-of-fun...,Smad2/3,nucleus,cytoplasm,None,reduced phosphorylation preventing nuclear tra...
18,{'context': {'perturbation_type': 'loss-of-fun...,SMAD2/3 complex,cytoplasm,nucleus,None,reduced phosphorylation
19,{'context': {'perturbation_type': 'loss-of-fun...,phosphorylated SMAD2/3,cytoplasm,nucleus,None,reduced phosphorylation
20,{'context': {'perturbation_type': 'loss-of-fun...,FOXO,cytoplasm,nucleus,None,FOXO re-activation
21,{'context': {'perturbation_type': 'loss-of-fun...,AKT,cytoplasm,plasma membrane,None,PIP3 accumulation
22,{'context': {'perturbation_type': 'loss-of-fun...,AKT,plasma membrane,cytoplasm,None,reduced PIP3 levels
24,{'context': {'perturbation_type': 'loss-of-fun...,AKT,cytosol,plasma membrane,None,reduced PIP3 levels
26,{'context': {'perturbation_type': 'soluble fac...,Smad complex,cytoplasm,nucleus,None,reduced Smad complex formation
27,{'context': {'perturbation_type': 'soluble fac...,SMAD2/3-SMAD4 complex,cytoplasm,nucleus,None,reduced complex formation
28,{'context': {'perturbation_type': 'soluble fac...,SMAD2/3/4 complex,cytoplasm,nucleus,None,reduced SMAD2/3 phosphorylation
29,{'context': {'perturbation_type': 'soluble fac...,Smad2/3-Smad4 complex,cytoplasm,nucleus,None,n3
30,{'context': {'perturbation_type': 'soluble fac...,SMAD complex,cytoplasm,nucleus,None,reduced SMAD complex formation
31,{'context': {'perturbation_type': 'loss-of-fun...,β-catenin,cytoplasm,nucleus,None,impaired degradation and stabilization
32,{'context': {'perturbation_type': 'loss-of-fun...,beta-catenin,cytoplasm,nucleus,None,accumulation
34,{'context': {'perturbation_type': 'loss-of-fun...,CTNNB1,cytoplasm,nucleus,None,increased cytoplasmic concentration
37,{'context': {'perturbation_type': 'loss-of-fun...,β-catenin,nucleus,membrane,None,attenuated Wnt signaling and restored GSK3β fu...
39,{'context': {'perturbation_type': 'loss-of-fun...,phosphorylated STAT dimers,cytoplasm,nucleus,None,decreased phosphorylation
40,{'context': {'perturbation_type': 'loss-of-fun...,STAT3,cytoplasm,nucleus,None,reduced phosphorylation
42,{'context': {'perturbation_type': 'loss-of-fun...,STAT3,nucleus,cytoplasm,None,reduced STAT3 phosphorylation
43,{'context': {'perturbation_type': 'loss-of-fun...,phosphorylated STAT3,cytoplasm,nucleus,None,STAT3 phosphorylation
44,{'context': {'perturbation_type': 'loss-of-fun...,phosphorylated STATs,cytoplasm,nucleus,None,reduced STAT phosphorylation
45,{'context': {'perturbation_type': 'loss-of-fun...,pSTAT3,None,nucleus,None,increased phosphorylation and dimerization
49,{'context': {'perturbation_type': 'soluble fac...,IFNAR1,cell surface,intracellular,internalization,Anifrolumab binding
50,{'context': {'perturbation_type': 'loss-of-fun...,HIF-2α/ARNT heterodimer,cytoplasm,nucleus,None,functional heterodimer formation
51,{'context': {'perturbation_type': 'loss-of-fun...,EPAS1,cytoplasm,nucleus,None,impaired HIF-2α/ARNT complex formation
52,{'context': {'perturbation_type': 'soluble fac...,NF-κB,cytoplasm,cytoplasm,None,"stable IκB sequestration, blocking nuclear tra..."
53,{'context': {'perturbation_type': 'soluble fac...,NF-κB complex,cytoplasm,nucleus,None,sequestration by NFKBIA
54,{'context': {'perturbation_type': 'soluble fac...,NF-κB,cytoplasm,nucleus,None,persistent IκBα binding
56,{'context': {'perturbation_type': 'soluble fac...,NF-κB dimers,cytoplasm,cytoplasm,None,IκB sequestration
57,{'context': {'perturbation_type': 'soluble fac...,ISGF3,cytoplasm,nucleus,None,inhibited ISGF3 complex formation
59,{'context': {'perturbation_type': 'soluble fac...,STAT1/2,cytoplasm,nucleus,None,impaired ISGF3 complex formation
64,{'context': {'perturbation_type': 'soluble fac...,NF-kappaB,cytoplasm,nucleus,None,n10
67,{'context': {'perturbation_type': 'soluble fac...,AKT,cytosol,membrane,None,decreased PIP3 levels
71,{'context': {'perturbation_type': 'soluble fac...,NF-κB,nucleus,cytoplasm,None,sequestration by stabilized IκB-α in the cytop...
72,{'context': {'perturbation_type': 'soluble fac...,NF-κB dimers,cytoplasm,nucleus,None,IκBα sequestration
74,{'context': {'perturbation_type': 'soluble fac...,STAT1,cytoplasm,nucleus,None,inhibited phosphorylation and dimerization
77,{'context': {'perturbation_type': 'soluble fac...,"STAT1, STAT3",cytoplasm,nucleus,None,inhibition of STAT phosphorylation
78,{'context': {'perturbation_type': 'soluble fac...,STAT1/STAT3,cytoplasm,nucleus,None,inhibited phosphorylation and dimerization
79,{'context': {'perturbation_type': 'soluble fac...,STAT1 dimer,cytoplasm,nucleus,None,reduced STAT1 dimerization
80,{'context': {'perturbation_type': 'soluble fac...,STAT1 homodimer,cytoplasm,nucleus,None,impaired dimerization
85,{'context': {'perturbation_type': 'soluble fac...,STAT,cytoplasm,nucleus,None,lack of phosphorylation and dimerization

### Define the SCLArgs

In [7]:
row = scl_data.iloc[0]
row

perturbation    {'context': {'perturbation_type': 'soluble fac...
entity                                                      STAT6
from_loc                                                cytoplasm
to_loc                                                    nucleus
mechanism                                                    None
modification           decreased phosphorylation and dimerization
Name: 0, dtype: object

In [8]:
sclv = SCLVerifier()

In [ ]:
for _, row in scl_data.iterrows():
    print("row: ", row.to_dict())
    args = SCLArgs(
        protein_entity=row["entity"],
        from_loc=row["from_loc"],
        to_loc=row["to_loc"],
        mechanism=row["mechanism"],
        modification=row["modification"],
    )
    # run verifier
    print(sclv._tool_logic(args))
    
    break

row:  {'perturbation': "{'context': {'perturbation_type': 'soluble factor', 'description': 'Soluble factor addition of IL-13', 'cell_type': 'N/A', 'disease_model': 'Asthma and allergy - IL-13'}, 'perturbation': {'type': 'chemical', 'smiles': None, 'name': 'Lebrikizumab', 'target': 'IL13', 'moa_type': 'antibody'}}", 'entity': 'STAT6', 'from_loc': 'cytoplasm', 'to_loc': 'nucleus', 'mechanism': None, 'modification': 'decreased phosphorylation and dimerization'}
2025-08-12 19:35:48,168 SequenceTagger predicts: Dictionary with 21 tags: O, S-Chemical, B-Chemical, E-Chemical, I-Chemical, S-Gene, B-Gene, E-Gene, I-Gene, S-Disease, B-Disease, E-Disease, I-Disease, S-Species, B-Species, E-Species, I-Species, S-CellLine, B-CellLine, E-CellLine, I-CellLine

2025-08-12 19:35:48.193 | INFO     | explain.eval.tools.bio.entity:retrieve_identifiers:152 - NER model info: hunflair2
2025-08-12 19:36:10.236 | INFO     | explain.eval.tools.bio.entity:_ID_mapping:102 - ID mapping.

(0.3, {'protein_entity': 'STAT6', 'from_loc': 'cytoplasm', 'to_loc': 'nucleus', 'mechanism': None, 'modification': 'decreased phosphorylation and dimerization', 'verification_status': 'NOT_VERIFIED'})